export const generarId = () => {
    const random = Math.random().toString(32).substring(2);
    const fecha = Date.now().toString(32);

    return random + fecha;
}

export const formatearHora = (fecha) => {
    const fechaNueva = new Date(fecha);

    const opcionesHora = { hour: '2-digit', minute: '2-digit', hour12: false };

    const resultado = `${fechaNueva.toLocaleTimeString('es-ES', opcionesHora)}`;

    return `${resultado}`;
};

export const formatearFecha = (fecha) => {
    const fechaNueva = new Date(fecha);

    const opcionesFecha = { year: 'numeric', month: '2-digit', day: '2-digit', timeZone: 'UTC' };

    // Usamos toLocaleDateString para obtener solo la parte de la fecha
    const resultadoFecha = fechaNueva.toLocaleDateString('es-ES', opcionesFecha);

    return resultadoFecha.replace(/\//g, '-'); // Reemplaza las barras por guiones
};

export const actividades = [
    "cerramiento provisional madera de monte",
    "cerramiento provisional metalico",
    "cerramiento de bloque de 15 cm",
    "cerramiento de ladri[lo mambron",
    "cerramiento de ladrillo jaboncillo",
    "cerramiento prefabricado de hormigon",
    "cerramiento de malla galvanizada",
    "contruccion bodegas y oficinas",
    "derrocamiento estructura existente",
    "rotura de pavimento",
    "limpieza de terreno",
    "replanteo",
    "desbanque y nivelacion de terreno",
    "excavacion de plintos y cimientos",
    "excavacion en roca",
    "excavacion con nivel freatico",
    "relleno compactado con tierra",
    "relleno compactado con lastre",
    "desalojo de material con volqueta",
    "desalojo de material con volqueta",
    "malla electrosoldada",
    "malla electrosoldada",
    "malla electrosoldada",
    "malla electrosoldada",
    "hierro 8mm",
    "hierro de 10mm",
    "hierro de 12mm",
    "hierro de 14mm",
    "hierro 16mm",
    "hierro 18mm",
    "hierro de 20mm",
    "hierro de 8 a 20mm",
    "replantillo en cimientos",
    "replantillo en plintos y vigas",
    "mamposteria de piedra",
    "hormigon ciclopleo, en cimentacion",
    "plintos hormigon ciclopeo",
    "hormigon en plintos",
    "hormigon en vigas de cimentacion",
    "hormigon en cadenas inferiores",
    "hormigon en columnas",
    "hormigon en escaleras",
    "mamposteria bloque estructural de 20 cm",
    "mamposteria jaboncillo prensado de 7cm",
    "mamposteria jaboncillo prensado de 10 cm",
    "mamposteria ladrillo alivianado de 8cm",
    "mamposteria ladrillo alivianado de 10 cm",
    "mamposteria iadrillo alivianado de 12cm",
    "mamposteria ladrillo alivianado de 14 cm",
    "paredes de hormigon",
    "revocado de 112 cana ladrillo visto",
    "revocado de 1/2 cana bloque visto",
    "revocado junta perdida en ladrillo",
    "00revocado junta perdida en bloque",
    "paneles plaicent fifrocemento",
    "paneles de madera (triplex marino)",
    "paneles de madera (triplex)",
    "paneles de hormigon prefabricado",
    "paneles Hormidos o Mdos",
    "paneles de cana gadua entera",
    "paneles de media cana gadua",
    "paneles tipo esterilla de cana gadua",
    "lavanderia jaboncillo 1 pozo + I piedra",
    "lavanderia jaboncillo 1 pozo + 2piedras",
    "lavanderia prefabricada de hormigon",
    "enlucido cielo razo",
    "eniucidos interiores",
    "enlucidos exteriores",
    "enlucidos de filos de ventana",
    "eniucidos de fajas",
    "medias canas",
    "macillado e impermiabilizacion",
    "cielo razo de malla",
    "cieio razo de estuco",
    "cieio razo de madera triplex",
    "cieio razo de fibro cemento",
    "cielo razo importado",
    "cielo razo gypsum",
    "contrapiso de hormigon",
    "macillado y alisado de pisos",
    "tejuelo",
    "baldosa de cemento",
    "gress",
    "ceramica de piso",
    "porcelanato",
    "marmol corte normal",
    "marmol tipo mapeado",
    "marmolina",
    "terrazo",
    "piso flotante",
    "vinyl de 1.5 mm",
    "vinyl de 1.8 rnm",
    "vinyl de 2.0 mm",
    "parquet de eucalipto tradicional",
    "parquetde chanul tradicional",
    "media duela de eucalipto",
    "media duela de chanul",
    "duela de eucalipto",
    "duela de chanul",
    "tabloncillo de chanul",
    "alfombra",
    "barredera de vinyl",
    "barredera de ceramica",
    "barredera de marmot",
    "barredera de caucho",
    "barredera de porcelanato",
    "barredera de madera",
    "barredera de mdf",
    "ceramica en banos",
    "cenefas de 6x25 cm",
    "cenefas de 10x30 cm",
    "cornisa",
    "ventana de hierro",
    "ventana corrediza de aluminio",
    "ventana fija de aluminio",
    "ventana de madera",
    "ventana de plastico",
    "reja de hierro fija",
    "reja de hierro plegable",
    "vidrio catedral",
    "vidrio esmerilado",
    "espejo",
    "vidrio de 3 mm",
    "vidrio de 4 mm",
    "vidrio de 5 mm",
    "vidrio de 6 mm",
    "vidrio de 8 mm",
    "ventana tipo lanfor",
    "vidrio templado de 3 mm",
    "vidrio templado de 4 mm",
    "vidrio templado de 5 mm",
    "vidrio templado de 6 mm",
    "biselado an vidrio",
    "vitrales",
    "puerta madera de 70 cm",
    "puerta madera de 80 cm",
    "puerta madera de 90 cm",
    "puerta madera de 100 cm",
    "puerta aluminio y vidrio",
    "puerta de hierro",
    "cerradura sobrepuesta p. hierro",
    "cerradura Ilave-Ilave",
    "cerradura llave-seguro",
    "cerradura de bane",
    "cerradura tipo cerrojo",
    "cerradura de paso",
    "closet con comodin",
    "muebles bajos de cocina",
    "muebles altos de cocina",
    "mueble tipo biblioteca",
    "muebles para lavamanos",
    "pasamanos de hierro",
    "pasamanos de hierra y madera",
    "pasamanos de aluminio",
    "pasamanos de aluminio y vidrio",
    "pintura caucho cielo raso",
    "pintura caucho interior",
    "pintura caucho exterior",
    "pintura cemento blanco",
    "pintura con carbonate",
    "pintura esmalte",
    "pintura para cubierta",
    "texturizados",
    "champeado",
    "chafado",
    "grafiado",
    "impermeabilizante permasil",
    "impermeabilizante paraguas",
    "plaquetas",
    "lavado piedra tallada",
    "pintura ladrillo visto",
    "laca puertas",
    "laca closet y otros muebles",
    "laca pisos",
    "pintura de cloro",
    "pintura para cisternas",
    "plancha ardex",
    "plancha eurolit P 7",
    "plancha eurolit P 10",
    "plancha eurolit espanola",
    "ecuateja clasica superior",
    "ecuateja colonial superior",
    "teja comun",
    "teja vidriada",
    "teja plana",
    "teja clasica",
    "traslucido fibra de vidrio ardex",
    "traslucido fibra de vidrio P 7",
    "traslucido fibra de vidrio P 10",
    "traslucido fibra de vidrio espanola",
    "traslucido termoformado P 7",
    "traslucido termoformado P 10",
    "traslucido termoformado espanola",
    "domos acrlicos",
    "cubierta metalica dura techo",
    "plancha de zing",
    "cubierta policarbonato",
    "teja asfaltica chova",
    "paja de paramo",
    "palma de costa",
    "viga de chanul de 7x14 cm",
    "viga de colorado de 7x14 cm",
    "alfagias de eucalipto",
    "viga de eucalipto redondo",
    "cuartones de colorado",
    "viga de cana gadua",
    "canal metalico u de 70x35x3 cm",
    "canal metalico u de I00x50x3 mm",
    "canal metalico u de 150x50x3 mm",
    "canal metalico u de 200x50x3 mm",
    "canal metalico u de 200x50x4 mm",
    "canal metalico u de 250x100x4 mm",
    "canal metalico u de 300x150x5 mm",
    "celocias de hierro",
    "tuberia PVC 50 mm",
    "tuberia PVC 75 mm",
    "tuberia PVC 110 mm",
    "tuberia PVC 160 mm",
    "canalizacion PVC de 50 mm",
    "canalizacion PVC de 75 mm",
    "canalizacion PVC de 110 mm",
    "canalizacion PVC de 160 mm",
    "rejilla de aluminio de 50 mm",
    "rejilla de aluminio de 75 mm",
    "rejilla de aluminio de 110 mm",
    "rejilla de aluminio de 160 mm",
    "ventilacion PVC de 50 mm",
    "ventilacion PVC de 75 mm",
    "ventilacion PVC de 110 mm",
    "tuberia de cemento de 100 mm",
    "tuberia de cemento de 150 mm",
    "tuberia de cemento de 200 mm",
    "tuberia asbesto cemento de 200 mm",
    "80caja de revision de ladrillo",
    "caja de revision de hormigon",
    "tuberia PVC roscable de 1/2\"",
    "tuberia PVC roscable de 3/4\"",
    "!84tuberia PVC roscable de 1\"",
    "tuberia PVC roscable de 11/2\"",
    "tuberia PVC roscable de 2",
    "salida de agua fria de 1/2\" en pvc",
    "salida de agua caliente de 1/2\" en pvc",
    "salida de agua fria de 1/2\" en hg",
    "salida de agua caliente de 1/2\" en hg",
    "salida de agua fria y caliente en cobre",
    "salida de agua fria y caliente en hidro 3",
    "llave campanola",
    "ducha cromada",
    "llave de control de 1/2",
    "llave de control 314",
    "llave de manguera de 1/2",
    "valvula check 1/2",
    "llave angula inodoro",
    "llave angular lavamanos",
    "llave angular lavaplatos",
    "mezciadora Iavamanos monocontrol",
    "mezcladora lavamanos de 4\"",
    "mezcladora Iavamanos de 8\"",
    "mezcladora lavaplatos monocontrol",
    "mezcladora lavaplatos de 8",
    "mezcladora ducha monocontrol",
    "mezcladora ducha de 8",
    "lavamanos",
    "lavamanos con pedestal",
    "lavamanos para mueble",
    "inodoro",
    "inodoro tanque integrado",
    "inodoro con fluxometro",
    "urinario",
    "urinario con fluxometro",
    "tina fibra de vidrio",
    "lavaplatos lpozo + 1 escurridera",
    "lavaplatos lpozo +2 escurrideras",
    "lavaplatos 2pozoz + 2 escurridera",
    "lavaplatos 1 pozo",
    "lavaplatos 2 pozos",
    "calefon de 10 Its",
    "calefon de 12 Its",
    "calefon de 16 Its",
    "calefon de 20 Its",
    "calefon de 24 Its",
    "tanque termostato de 20 gis",
    "tanque termostato de 30 gis",
    "calentador solar",
    "gabinete de bano",
    "tuberia conduit de 1/2\"",
    "tuberia conduot de 3/4",
    "tuberia conduit de 1",
    "tuberia conduit de 1 1/2",
    "tuberia conduit de 2",
    "tablero monofasico de 4-8 breaker",
    "tablero bifasico de 8 - 12",
    "tablero trifasico de 12 - 24 breaker",
    "acometida monofasica conductor No. 8",
    "acometida bifasica conductor No. 8",
    "acometida trifasica conductor No. 8",
    "acometida bifasica cable blindado No. 8",
    "iluminacion",
    "toma corriente",
    "toma corriente especial",
    "tomacorriente polarizado",
    "iluminacion cable plastiplorno",
    "tomacorriente cable plastiplomo",
    "acometida de telefono",
    "panto telefono",
    "acometida de television",
    "puntos de television",
    "intercom unicador",
    "puntos de intercomunicador",
    "ducha electrica",
    "encespado",
    "jardinera",
    "pavimento exterior peatonal",
    "pavimento exterior acc. Vehicular",
    "veredas perimetrales hormigon",
    "veredas con adoquin cemento",
    "veredas con adoquin arcilla",
    "adoquinado",
    "porton de hierro de 3mts.",
    "puerta corrediza de 3,50m",
    "limpieza final de la obra",
    "instalacion de medidor de gas",
    "tanque de gas centraiizado",
    "instalacion de medidor de agua potable",
    "instalacion de medidor de energia elect.",
    "tablero de medidores 8 unid.",
    "tablero de medidores 12 unid.",
    "tablero de medidores 24 unid.",
    "bisera de hormigon",
    "bisera de madera y teja"
]